name: Build Typst document
on: [push]
permissions:
  contents: write
jobs:
  build_typst:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Typst
        uses: typst-community/setup-typst@v4
      - name: Compile
        uses: Jarivanbakel/typst-action@v3
        with:
          input_files: main.typ
      - name: Upload
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          name: PDF
          path: malalengua.pdf