name: Build Typst document
on: [push]
jobs:
  build_typst:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses:  Jarivanbakel/typst-action@v3
        with:
          input_files: main.typ
      - name: Upload PDF file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          name: PDF
          path: malalengua.pdf